/** Response of `GET /api/v1/projects/:slug/keys`. */
export interface KeysResponse {
  project: string;
  baseLocale: string;
  locales: string[];
  keys: { key: string; description: string | null; placeholders: string[] }[];
}

export type Format = "ts" | "php" | "rust";

export interface GenerateOptions {
  /** PHP only: namespace for the generated class. */
  phpNamespace?: string;
  /** PHP only: class name (default "Keys"). */
  phpClass?: string;
}

const header = (project: string) =>
  `Generated by \`lucent-translate generate\` from project "${project}". Do not edit;\n` +
  `regenerate after adding, renaming or removing keys.`;

export function generate(data: KeysResponse, format: Format, options: GenerateOptions = {}): string {
  switch (format) {
    case "ts":
      return generateTypeScript(data);
    case "php":
      return generatePhp(data, options);
    case "rust":
      return generateRust(data);
  }
}

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const propertyName = (name: string) => (IDENTIFIER.test(name) ? name : JSON.stringify(name));

function docLines(description: string | null, placeholders: string[], indent: string, style: "jsdoc" | "rust") {
  const lines = [
    ...(description ? description.split(/\r?\n/) : []),
    ...(placeholders.length ? [`Params: ${placeholders.map((p) => `{${p}}`).join(", ")}`] : []),
  ];
  if (lines.length === 0) return "";
  if (style === "rust") return lines.map((l) => `${indent}/// ${l}\n`).join("");
  const safe = lines.map((l) => l.replaceAll("*/", "*\\/"));
  return safe.length === 1
    ? `${indent}/** ${safe[0]} */\n`
    : `${indent}/**\n${safe.map((l) => `${indent} * ${l}`).join("\n")}\n${indent} */\n`;
}

function generateTypeScript(data: KeysResponse): string {
  const entries = data.keys
    .map(({ key, description, placeholders }) => {
      const params = placeholders.length
        ? `{ ${placeholders.map((p) => `${propertyName(p)}: string | number`).join("; ")} }`
        : "{}";
      return `${docLines(description, placeholders, "    ", "jsdoc")}    ${JSON.stringify(key)}: ${params};`;
    })
    .join("\n");

  return `${header(data.project).replace(/^/gm, "// ")}
/* eslint-disable */
import "@lucent-translate/sdk";

declare module "@lucent-translate/sdk" {
  interface TranslationKeys {
${entries}
  }
}
`;
}

/** SCREAMING_SNAKE constant names; throws if two keys map to the same name. */
function constantNames(keys: KeysResponse["keys"]): Map<string, string> {
  const names = new Map<string, string>();
  const owners = new Map<string, string>();
  for (const { key } of keys) {
    let name = key
      .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
      .replace(/[^A-Za-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .toUpperCase();
    if (!name || /^\d/.test(name)) name = `KEY_${name}`;
    const clash = owners.get(name);
    if (clash) {
      throw new Error(`Keys "${clash}" and "${key}" both become the constant ${name}; rename one of them.`);
    }
    owners.set(name, key);
    names.set(key, name);
  }
  return names;
}

function generatePhp(data: KeysResponse, options: GenerateOptions): string {
  const names = constantNames(data.keys);
  const className = options.phpClass ?? "Keys";
  const constants = data.keys
    .map(({ key, description, placeholders }) => {
      const literal = `'${key.replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
      return `${docLines(description, placeholders, "    ", "jsdoc")}    public const ${names.get(key)} = ${literal};`;
    })
    .join("\n\n");

  return `<?php

${header(data.project).replace(/^/gm, "// ")}

declare(strict_types=1);
${options.phpNamespace ? `\nnamespace ${options.phpNamespace};\n` : ""}
/** Translation keys of project "${data.project}". */
final class ${className}
{
${constants}
}
`;
}

function generateRust(data: KeysResponse): string {
  const names = constantNames(data.keys);
  const constants = data.keys
    .map(
      ({ key, description, placeholders }) =>
        `${docLines(description, placeholders, "", "rust")}pub const ${names.get(key)}: &str = ${JSON.stringify(key)};`,
    )
    .join("\n\n");

  return `${header(data.project).replace(/^/gm, "// ")}
#![allow(dead_code)]

${constants}
`;
}
