// Generated by `lucent-translate generate` from project "demo-app". Do not edit;
// regenerate after adding, renaming or removing keys.
/* eslint-disable */
import "@lucent-translate/sdk";

declare module "@lucent-translate/sdk" {
  interface TranslationKeys {
    /** Params: {name} */
    "home.subtitle": { name: string | number };
    "home.title": {};
  }
}
